WindowManager:
  IntroWindow:
  SearchWindow:
  

<IntroWindow>:
  FloatLayout:
    size_hint: 1,1

    Label:
      halign: "center"
      text_size: self.size
      text: "Youtube URL to Mp3/Mp4 Converter"
      font_size:'60'
      size_hint: 0.9,0.9
      pos_hint: {"top" : 1.3, "right" : 0.95}
      background_color: (0,0,0,0)
      canvas.before:
        Color:
          rgba: self.background_color
        Rectangle:
          size: self.size
          pos: self.pos
      color: (1,0,0,1)
      bold: True
      outline_color: (1,1,1)
      outline_width: 1.5

    Button:
      text: "Run Program"
      font_size: '25'
      font_size: (root.width**2) / 11**4
      size_hint: 0.4,0.2
      pos_hint: {"top" : 0.3, "right" : 0.7}
      background_color: (0,0,1,1)
      on_release:
        root.manager.transition.direction = "up"
        app.root.current = "program"
    
<SearchWindow>:
  name: "program"
  url1: url1

  FloatLayout: #This creates the border around the stuff
    size_hint: 0.8,0.8 # Decreases the size dynamically
    pos_hint: {"top" : 1, "right" : 0.9} # Centers the stuff
            
    Label:
      font_size:'48'
      font_size: (root.width**2) / 11**4
      text: "Youtube URL to Mp3/Mp4 Converter"
      size_hint: 0.9,0.9
      pos_hint: {"top" : 1.3, "right" : 0.95}
      background_color: (0,0,0,0)
      canvas.before:
        Color:
          rgba: self.background_color
        Rectangle:
          size: self.size
          pos: self.pos
      color: (1,0,0,1)
      bold: True
      outline_color: (1,1,1)
      outline_width: 1.2

  FloatLayout:
    size_hint: 1, 1

    Label:
      size_hint: 1, 0.2
      pos_hint: {"top":0.8}
      text: "Enter Youtube URL here:"
      halign: "center"
      font_size: (root.width**2) / 11**4

    TextInput:
      size_hint: 1,0.1
      pos_hint: {"top" : 0.6}
      id: url1
      multiline: False
      font_size: '36'


  GridLayout:
    cols:2
    size_hint: 1,0.2
    pos_hint: {"bottom": 1}

    Button:
      text: "Mp3"
      font_size: '40'
      background_normal: ''
      background_color: (0,0,1,1)
      on_release:
        root.mp3()

    Button:
      text: "Mp4"
      font_size: '40'
      background_normal: ''
      background_color: (1,0,0)
      on_release:
        root.mp4()
